#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: ssk123456
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 6000


mybatis:
  type-aliases-package: com.ssk.mode
  mapperLocations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true


#item:
#  search:
#    sort: "{index_item: 'value1', key2: 'value2'}"